### ISSUE TITLE
Name monopoly

### ISSUE THREAD

**Issue by ghost** [genotrance/nimssl#1]
I have built a Nim wrapper for OpenSSL's RSA library and a couple of others. I would submit a pull request to add it to nimssl, but it uses the new nimterop library rather than nimgen. I suspect it would be very easy to wrap the rest of libcrypto with nimterop, but it feels pointless considering that this project already has the package name of nimssl on nimble. Would the maintainer (@genotrance) be interested in moving nimssl to nimterop (and the continuing to actively maintain it) or allowing me to re-assign the nimble listing to my own, more complete nimssl?

**Comment by dizzyliam** [comment]
Oops, didn't mean to close this. My package will be nimcrypto for now, but they could merge later.

**Comment by genotrance** [comment]
Let's reuse this project. See nimarchive which went thru a similar migration.
