### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by Peter2121** [genotrance/nimssl#4]
nimble v0.11.0
Nim Compiler Version 1.0.6
FreeBSD 11.3-RELEASE-p6
OpenSSL 1.0.2s

```
% nimble install nimssl
Downloading https://github.com/genotrance/nimssl using git
Setting up Git repo: https://github.com/openssl/openssl.git
Pulling repository
Creating nimssl/include/openssl/opensslconf.h
Processing nimssl/include/openssl/sha.h
Processing nimssl/include/openssl/macros.h
File doesn't exist: openssl/opensslv.h
stack trace: (most recent call last)
/tmp/nimblecache/nimscriptapi.nim(177, 29)
/tmp/nimble_44882/githubcom_genotrancenimssl/nimssl_44882.nims(32, 12) installBefore
/tmp/nimble_44882/githubcom_genotrancenimssl/nimssl_44882.nims(29, 8) setupTask
/usr/local/lib/system/nimscript.nim(252, 7) exec
/usr/local/lib/system/nimscript.nim(252, 7) Error: unhandled exception: FAILED: nimgen nimssl.cfg [OSError]
```

**Comment by genotrance** [comment]
Hello @Peter2121 - what portions of openssl were you needing?

See [rsa.nim](https://github.com/nimterop/nimterop/blob/master/tests/rsa.nim) for an example of how to wrap multiple openssl headers.

nimssl is kind of on hold right now since I'm not sure what combination of headers people might need. The way openssl is organized, there's no real top-level header that people are expected to import, and wrapping everything is too slow.

**Comment by Peter2121** [comment]
I needed some RSA related functions (read key, check key, ...)
Finally, I found another solution, but the wrapper still seems to be interesting for me (in other projects). 
In general, IMHO it would be nice to provide several wrappers (to accelerate the build when one needs just one or two) for different parts of openssl library. But I have no idea about the correct way of splitting it :)
How do another languages (python?) solve this problem?
Anyway, I think that if you can create a wrapper for everything (even if it is too slow) - it could be acceptable in many cases.

**Comment by darkr4y** [comment]
According to my attempts:
I found that [nimgen](https://github.com/genotrance/nimgen) is used when generating this project.
The configuration can be found in the `nimssl.cfg` file (download from the project's releases, do not use the code where from branch master), the `openssl/opensslv.h` file hasn't exist in the OpenSSL project now, in its place there is the `include/openssl/opensslv.h.in` file.  `.in` file extension is provided to the `configure` command is used to be configured the  macros of a project, common operations such as `./configure --prefix=/usr`
I'm not sure if fixing this problem requires updating nimgen to provide support for `configure` operations, and also I'm not sure if Mingw on windows has already provided this command.

**Comment by genotrance** [comment]
I'd really try using nimterop going forward, nimgen is pretty much archived at this point.

You can use rsa.nim linked above as the base and import different headers depending on the project needs. If you have good variations then I'll be happy to merge PRs here.

**Comment by darkr4y** [comment]
OK, I will try it.
Also I'm learning Nimterop for the first time by trying to package Wolfssl, and there are some [problems](https://github.com/nimterop/nimterop/issues/261), so it would be great if you could help!
